version: "3.3"
services:
  db:
    container_name: 'redis-db'
    image: redis:latest
    restart: unless-stopped
  app:
    container_name: 'slack_bot'
    env_file:
      - .env.production
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - db
    ports:
      - "3000:3000"

